gems:
  - jekyll/scholar
  - jekyll-last-modified-at
  - jekyll-paginate

timezone: Europe/Paris

# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            'Alexis Duque'

tagline:          'Director of Research at Rtone.'
description:      'Director of Research @Rtone<br>Ph.D. #iot #ml #vlc #security 💡🔑🚴‍'
url:              http://alexisduque.me
baseurl:          ''
update: 'September 15th, 2020'
paginate: 5
paginate_path: "/news/page:num/"

author:
  name: 'Alexis Duque'
  email: 'alexisd61@gmail.com'
  github: alexisduque
  twitter: alexis0duque
  linkedin: alexisduque
  google_scholar: https://scholar.google.fr/citations?user=P9BIZW0AAAAJ
  email_md5: 83124b745752d1a1b0ca2eee1af0bd48
  disqus_shortname: alexisduque
  bio: Director of Research at Rtone. Ph.D. in Computer Science.
  google_analytics_id: 'UA-73113604-1'
  google_analytics_url: 'auto'
# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/alexisduque/alexisduque.github.io

scholar:
  style: apa
  locale: en

  sort_by: none
  order: ascending

  source: ./_bibliography
  bibliography: references.bib
  bibliography_template: "{{reference}}"

  replace_strings: true
  join_strings:    true

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"
